server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  datasource:
    initialization-mode: always
    url:
    driver-class-name: org.postgresql.Driver
    username:
    password: